### ISSUE TITLE
Alternative type of secure aggregation

### ISSUE THREAD

**Issue by codablock** [Chia-Network/bls-signatures#18]
I was thinking about an alternative type of secure aggregation that prevents the rogue key attack. I'm not sure if this is really secure, so I'm looking for some feedback/analysis. If it is secure, it might be a simpler alternative to make aggregation secure.

There are currently 3 way that I know of to prevent the rogue key attack:
1. Make all messages distinct by including the public key when hashing the message. This however slows down verification of aggregated signatures as it requires the pairing function for every message.
2. Require proof of possessions (PoP) beforehand, meaning that for every public key there must be a signature present that signs the public key itself. This way it's ensured that the public key belongs to a secret key that is actually in the possession of the issuer of a signature. This is considered unpractical when it comes to signatures inside Bitcoin-like transactions as it would require to include a signature into all transaction outputs.
3. The way this library implements aggregation and verification, based on this [paper](https://crypto.stanford.edu/~dabo/pubs/papers/BLSmultisig.html)

The alternative that I was thinking about is a modified version of 2. Instead of requiring the PoP beforehand, each aggregation of same-message signatures would required to aggregate an "aggregated PoP" as well.
1.  _H(m)_ is signed with _pk<sub>1</sub>_..._pk<sub>n</sub>, creating σ<sub>1</sub>...σ<sub>n</sub>
2. A PoP message is created from all involved public keys: _H(pk<sub>1</sub>...pk<sub>n</sub>)_
3. _H(pk<sub>1</sub>...pk<sub>n</sub>)_ is signed with _pk<sub>1</sub>...pk<sub>n</sub>_, creating σ'<sub>1</sub>...σ'<sub>n</sub>
4. The final aggregated signature is _σ=agg(σ<sub>1</sub>...σ<sub>n</sub>, σ'<sub>1</sub>...σ'<sub>n</sub>)_

Verification is then: _e(g<sub>1</sub>, σ) = e(agg(pk<sub>1</sub>...pk<sub>n</sub>), H(m)) * e(agg(pk<sub>1</sub>...pk<sub>n</sub>), H(pk<sub>1</sub>...pk<sub>n</sub>))_

It's basically a verification of an aggregate signature with 2 distinct messages. Downside is that it requires one additional pairing per same-message aggregation.

These aggregated signatures can easily be aggregated with other aggregated signatures. It still requires to keep track of the public keys involved for every same-message aggregation, but it becomes a simple list instead of a tree. If such an aggregated signature is successfully verified, some form of caching can be used to store the information that the included PoPs were valid. Next time the same PoP appears inside an aggregated signature, signature division can be used to remove the PoP from the aggregated signature so that the extra pairing can be skipped.

I'm not sure about the security of this and if it really prevents the rogue public key attack (I'm far from being a cryptographer/mathematician) . Happy to have some feedback :)

**Comment by mariano54** [comment]
It's still not secure against the rogue public key attack. The attacker can set their pk pk2, as (g^alpha * pk1 ^ -1). Since you are using simple public key aggregation here, the public keys are just multiplied together, and thus the attacker can cancel out the other person's public key, assuming he knows their public key. 

The proof of possession defense works because each person is signing a different message (their own pk). If you make them all sign the same thing, it's vulnerable to the same attack. 

Furthermore, it's not clear how a user would obtain all the other user's public keys, and how they would agree on what to sign. In the bitcoin (and chia) model, a user can submit their transaction which reveals their pk and spends, and does not have to coordinate with others. 

The only thing I can think of, to get a constant size proof of possession, is using a recursive snark where people pass the snark around and add their public key to it... But I have no idea how practical this is from a proving time, and it also requires an interactive protocol. Or do some sort of commit reveal scheme, where public keys are kept secret, so the attacker can not find out the victim's key.. but that's also interactive, requires bandwidth, has DOS issues, etc..

**Comment by codablock** [comment]
Ok I see and kind of already expected this to be not secure. And I now start to better understand the rogue public key attack. The attacker is basically "removing" the public key of the victim from the aggregated public key and then signs the message with some kind of "fake" (alpha) private key.

Closing this issue now.
