### ISSUE TITLE
BLS Objects via pointers

### ISSUE THREAD

**Issue by kayabaNerve** [Chia-Network/bls-signatures#50]
Hello!

I wrapped this so it can be used via Nim. Due to how the default constructors are locked off, and because C++ will call a constructor on declaration, and because Nim declares all variables at the top of the file, they flat out do not work.

That said, I'm not an asshole asking for you to change the API for my unique use case. I found a solution, which was to make everything a pointer, as that does not call a constructor for you.

This was partially fixed in my previous issue here https://github.com/Chia-Network/bls-signatures/issues/38

That said, it was not totally fixed. In the AggregationInfo `=` operator, `Clear` is called before `InsertIntoTree`. `Clear` works, but if AggregationInfo is a pointer, no tree exists, and `InsertIntoTree` fails.

My solution was the following diff file which recreates the tree every time after clearing it.

```
diff --git a/src/aggregationinfo.cpp b/src/aggregationinfo.cpp
index 0cefddd..690ceed 100644
--- a/src/aggregationinfo.cpp
+++ b/src/aggregationinfo.cpp
@@ -245,6 +245,7 @@ std::ostream &operator<<(std::ostream &os, AggregationInfo const &a) {

 AggregationInfo& AggregationInfo::operator=(const AggregationInfo &rhs) {
     Clear();
+    tree = AggregationInfo::AggregationTree();
     InsertIntoTree(tree, rhs);
     SortIntoVectors(sortedMessageHashes, sortedPubKeys, tree);
     return *this;
```

However, this is unoptimized. It only needs to be done once (because then the tree exists and we can move on), yet always runs, even if the object isn't a pointer in the first place. It also may be a memory leak? I haven't coded C++ in a while and forgot if class members of pointers linger.

**Comment by codablock** [comment]
I also got some issues with the way constructors are implemented in the lib, which forced me to use a patched version it where I simply make the constructors public. I assume this will be a problem for much more people as it makes use of the library unnecessarily hard.

An example use case where this is a problem is for example a serialized structure in Bitcoin based code that has a BLS primitive as member. In that case, there must be a default constructor available as initialization only happens at deserialization time.

To add default public constructors, all BLS primitives would have to track their validity state, as otherwise you might later end up using uninitialized objects. A simple boolean that is initialized to false in the default constructor would do. This boolean must then be checked everytime before the members are used in any way. I didn't find time yet to implement this for the upstream repo, maybe someone else can do this?

**Comment by kayabaNerve** [comment]
That's another option! I think all the devs I've talked to about this do exactly that.

That said, while it's a good idea in my opinion, and would allow Nim to use non-pointer BLS objects, it doesn't fix pointer BLS objects, and is an API change, while this issue is a bug fix. We may want to create a new issue about making the default constructors public.

**Comment by emlowe** [comment]
Closing issue
