### ISSUE TITLE
Potential bug in Signature deserialization and aggregation using Python

### ISSUE THREAD

**Issue by ycryptx** [Chia-Network/bls-signatures#54]
```
_seed = bytes([0, 50, 6, 244, 24, 199, 1, 25, 52, 88, 192,
                19, 18, 12, 89, 6, 220, 18, 102, 58, 209,
                82, 12, 62, 89, 110, 182, 9, 44, 20, 254, 22])

msg = b'NSAWatches'
privates = [PrivateKey.from_seed(_seed).serialize() for i in range(5)]
sigs = [PrivateKey.from_bytes(i).sign(msg).serialize() for i in privates]
_sigs = [Signature.from_bytes(i) for i in sigs]
assert Signature.aggregate(_sigs), "failing on aggregate"
```

Produces a runtime error, unknown exception

**Comment by mhchia** [comment]
After tracing and testing the cpp code, I think the exception is from https://github.com/Chia-Network/bls-signatures/blob/802bc2b2d7be33a309ece87ee0c32f547a2ad8d7/src/signature.cpp#L345-L347
This is because that a signature lacks the `AggregationInfo`. It can be simply solved by setting all signatures with their corresponding `message_hash` and `public_key`, before calling `Signature.aggregate`.

However, in my use case, I have a function `aggregate_signatures(Sequence[bytes]: signatures)` whose inputs are only raw bytes of the signatures, without any knowledge of message hashes and public keys. I can work around with this RuntimeError by exposing `Signature::AggregateSigsSimple` to the Python side, when calling `Signature.aggregate` with signatures having no aggregation info. I haven't understood the code inside `Signature::Aggregate` enough to determine whether exposing `AggregateSigsSimple` is a bad idea. It will be really helpful if anyone can direct me on this.

Another dumb question, is the `std::string str(b)` necessary in https://github.com/Chia-Network/bls-signatures/pull/57/files#diff-550e7950330ae6cb2a4a407140895bc9R143?

**Comment by mhchia** [comment]
cc @nmarley @mariano54 Will really appreciate having you guys' input on this issue and my questions.

**Comment by mariano54** [comment]
The reason for not exposing it, is that it's insecure when used naively. If you verify an aggregate signature of the SAME message, with different public keys (using simple aggregation), this signature can be forged, due to the rogue public key attack(https://crypto.stanford.edu/~dabo/pubs/papers/BLSmultisig.html). Therefore there is a special aggregation that needs to be done (Signature.aggregate) which takes care of the attack, but it requires setting the aggregationInfo. Furthermore, the verifier needs to set the aggregation info in the same way that it was set when signing. 

There are two alternatives which remove the need for that:
1. Each participant proves knowledge of their secret key, for example by signing their public key. Then it's safe to use PrivateKey.sign_insecure, and Signature.aggregate_insecure (which is the same as aggregate_simple). This makes it impossible for the above attack to happen.
2. Use PrivateKey.sign_prepend. This makes all the messages DIFFERENT by prepending the pk, and therefore also protects against the attack.

We need to convert from py::bytes to uint8_t*, so std::string is one way to do that.

**Comment by mhchia** [comment]
Big thanks for the answers. They make a lot of sense to me. I will see how to adapt our wrapper to the API. For me, this issue should probably have been solved since the runtime error is just because of the empty attestations.
